### ISSUE TITLE
support browse mode natively.

### ISSUE THREAD

**Issue by derekriemer** [ChrisDuffley/objPad#1]
If the current object has a tree interceptor, if that tree interceptor natively supports browse mode, let the tree interceptor handle browse mode, and only move out of that document if and when browse mode is no longer natively supported. This would be a useful thing to add to core as well, enhancing touch screen support.

**Comment by josephsl** [comment]
Hi, would you like to work on this? It’ll require some thinking before proceeding. Thanks.

**Comment by josephsl** [comment]
No update since 2016, closing as end of life.
