### ISSUE TITLE
Review modes are not supported on braille displays

### ISSUE THREAD

**Issue by Adriani90** [ChrisDuffley/objPad#4]
Hello Joseph,

first of all thank you for this great addon which is being used by many users.

Is it possible to introduce braille display support for this addon?

**Comment by Adriani90** [comment]
@Leonardder

**Comment by AAClause** [comment]
Hello,
If you want, I have a small fix for that.

**Comment by AAClause** [comment]
I've just been tested the latest code on master.
No problem with braille and the next version of NVDA.

**Comment by Adriani90** [comment]
@Andre9642 thank you for testing. I had NVDA 2017.4 since I have Problems downloading the next snapshots. Nice to hear that it works well in the next Version.

**Comment by josephsl** [comment]
Hi, I’ll write a note telling users to use 2018.1 (once it ships) as it includes much needed enhancements for automatic tethering, a feature that the add-on already supports. Thanks.

**Comment by josephsl** [comment]
Hi, in this case, I’ll leave this open until 2018.1 ships, at which point this will be closed as “worksforme” and “newnvdaversionrequired”. Thanks.

**Comment by AAClause** [comment]
> I had NVDA 2017.4 since I have Problems downloading the next snapshots. 
This problem seems resolved now.

**Comment by Adriani90** [comment]
Closing as works for me
