### ISSUE TITLE
objPad.po missing translation entry

### ISSUE THREAD

**Issue by dpy013** [ChrisDuffley/objPad#5]
Hello josephsl, I translated the objPad plugin and tested it. I found that the webpage elements were not translated. In the process of browsing the webpage, it is still in English. Here is an example:
#Web navigation:
	# Web elements list:
	webBrowseElements=(u"正常", u"链接", u"表单字段", u"标题", u"框架", 
u"表格", u"列表", u"路标")
	webBrowseMode = 0
	#Web navigation:
	# Web elements list:
	webBrowseElements=("normal", "Link", "Form field", "Heading", 
"Frame", "Table", "List", "Landmark")
	webBrowseMode = 0

**Comment by dpy013** [comment]
Hello josephsl, I translated the objPad plugin and tested it. I found that the webpage elements were not translated. In the process of browsing the webpage, it is still in English. Here is an example: #Web navigation: # Web elements list: webBrowseElements=(u"normal", u"link", u"form field", u"title", u"frame", u"table", u"list", u"roadmap")

**Comment by dpy013** [comment]
Here is my operation log:
[nvda.log](https://github.com/josephsl/objPad/files/2363291/nvda.log)

**Comment by josephsl** [comment]
Hi, I’ll correct this before end of 2018.
